# Generated by Django 2.2.2 on 2019-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
