# Generated by Django 2.2.2 on 2019-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190624_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tech',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
